print(25+15)
print(50-18)
print(12*8)
print(49/7)
print(25%4)
print(5**3)
print(17//3)
a=str(input("Enter an integer: "))
b=int(a)
print(b+10)
c=str(input("Enter an decimal value: "))
d=float(c)
print(d*2)
e=int(input("Enter an integer: "))
f=str(e)
print(e,f,type(e),type(f),sep="\n")